### PR TITLE
Rederived L1PF calibration files based on HGCal TPs from CMSSW 11_1_0_patch2

### PR DESCRIPTION
**Pull request by gpetruc**
Rederived L1PF calibration files based on HGCal V11 TPs from CMSSW `11_1_0_patch2` .
The previous set was derived on CMSSW `11_1_0_pre6`, and the difference is mostly visible at large |&eta;| values where the new release has more clusters and more energy.

#### Single particle response
* HGCal:  
   * Plot for pions [old calib](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr/ParticleGun_PU0/?match=pion*25_30*debug-hgc_pt02) & [new calib](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr.2/ParticleGun_PU0/?match=pion*25_30*debug-hgc_pt02)
   * Plot for photons [old](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr/ParticleGun_PU0/?match=photon*25_30*debug-hgc_pt02) & [new](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr.2/ParticleGun_PU0/?match=photon*25_30*debug-hgc_pt02)
 * HF, since HGCal inputs are added to HF towers at low |&eta;|  (3.0 - 3.2 or so)
    * Plots [old](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr/ParticleGun_PU0/?match=mixmix*30_32*ebug-hf_pt02), [new](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/corr.2/ParticleGun_PU0/?match=mixmix*30_32*ebug-hf_pt02) ;  it's still not spot on, but it's a difficult region.

#### Jet energy corrections

### CODE REVIEW

**Comment by silviodonato** [comment]
please test for CMSSW_11_1_X

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
merge
I will run the test on the cmsdist PR both for 11_1_X and 11_2_X

**Comment by rekovic** [comment]
+1

**Pull request merged**
