### PR TITLE
Update files that have been removed in https://github.com/cms-sw/cmssw/pull/41279

### PR DESCRIPTION
**Pull request by aloeliger**
This PR adds the model file and jecs root file in approximately the locations they were removed from in https://github.com/cms-sw/cmssw/pull/41279

@thesps @slaurila @thomreis @cerminar @drankincms & @gpetruc: could you please confirm that you are okay with this arrangement in the data externals?

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- Needed by #41279

**Comment by perrotta** [comment]
merge

**Pull request merged**
