### PR TITLE
New Conifer model for Composite TkElectron ID

### PR DESCRIPTION
**Pull request by cerminar**
Add BDT model to the data of the package.

Tagging @aloeliger  to keep him informed.

### CODE REVIEW

**Comment by aloeliger** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by AdrianoDee** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41647

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/41290 was merged without this PR, and now a unit test in `SLHCUpgradeSimulations/Geometry` seems to be failing because of that.

**Comment by perrotta** [comment]
+1
- To go together with https://github.com/cms-sw/cmssw/pull/41290 (thank you @makortel )

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
merge

**Pull request merged**
