### PR TITLE
[L1T] Phase-2, updated jecs

### PR DESCRIPTION
**Pull request by cecilecaillol**
Updated JECs for Phase2 jets

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
@smuzaffar, @aandvalenzuela, @iarspider, @cmsbuild, @AdrianoDee, @srimanob Can you please sign to merge the jec calibrations for L1 phase-2?

**Comment by AdrianoDee** [comment]
+1

**Comment by perrotta** [comment]
+1
- It has to go, and it was tested together wirh #38442

**Comment by perrotta** [comment]
merge

**Pull request merged**
