### PR TITLE
Add retrained tau model

### PR DESCRIPTION
**Pull request by Duchstf**
Hello, this is a PR to update the tau NN in association with this PR: https://github.com/cms-l1t-offline/cmssw/pull/1087

Duc.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41492

**Comment by aloeliger** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade
(Would wait for [#41492](https://github.com/cms-sw/cmssw/pull/41492))

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
@smuzaffar @iarspider Ping on this, this is related to a PR that has been merged for some time now.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
